# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proto

import flatbuffers

class Order(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOrder(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Order()
        x.Init(buf, n + offset)
        return x

    # Order
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Order
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def OrderStart(builder): builder.StartObject(1)
def OrderAddId(builder, id): builder.PrependUint32Slot(0, id, 0)
def OrderEnd(builder): return builder.EndObject()
